### ISSUE TITLE
流程图画好后保存在哪里？

### ISSUE THREAD

**Issue by ghost** [hs-web/hsweb-flowable-modeler#1]
流程图画好后保存成  .bpmn20.xml 的文件存在哪里。

**Comment by zhou-hao** [comment]
这个是flowbale的模型设计器,模型是以json保存在数据库的,你可以导出为 bpmn20.xml.具体的导出方法可以查看：

https://github.com/hs-web/hsweb-framework/blob/8a4cfabda14a362ce205f5fb6e43d48db5a4de57/hsweb-system/hsweb-system-workflow/hsweb-system-workflow-local/src/main/java/org/hswebframework/web/workflow/web/FlowableModelManagerController.java#L135-L187

**Comment by ghost** [comment]
十分感谢，问题已经解决了。
